hydra:
  run:
    dir: outputs/qa_inference/${dataset.data_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}

defaults:
  - _self_
  - text_emb_model: multi5
  - doc_ranker: idf_topk_ranker
  - qa_prompt: medqa
  - qa_evaluator: medqa

seed: 1024

dataset:
  root: E:\arag\gfm-rag\data  # Sửa đường dẫn cho Linux/WSL compatibility
  data_name: vietnamese_medical

llm:
  _target_: gfmrag.llms.ChatGPT
  model_name_or_path: gpt-4o-mini
  base_url: https://api.yescale.io/v1
  retry: 5

graph_retriever:
  model_path: E:\arag\gfm-rag\gfm_model
  doc_ranker: ${doc_ranker}
  ner_model: ${ner_model}
  el_model: ${el_model}
  qa_evaluator: ${qa_evaluator}
  init_entities_weight: True

test:
  retrieval_batch_size: 1
  top_k: 5
  save_retrieval: False
  save_top_k_entity: 10
  n_threads: 5
  retrieved_result_path: null
  prediction_result_path: null
  init_entities_weight: True
  max_test_samples: 1

doc_ranker:
  _target_: gfmrag.doc_rankers.IDFWeightedTopKRanker
  top_k: 30
