_target_: gfmrag.kg_construction.entity_linking_model.DPRELModel
model_name: dangvantuan/vietnamese-embedding
use_cache: True
normalize: True
batch_size: 1
sim_batch_size: 8
chunk_size: 5
query_instruct: "query: "
passage_instruct: "passage: "